### ISSUE TITLE
Why are the dates required in the simplified json file?

### ISSUE THREAD

**Issue by MilesQLi** [malicialab/avclass#13]
I assume the scan date and first seen date are not important. Why do you need them?

**Comment by malicialab** [comment]
I guess we never answered this one, apologies for that. scan_date and first_seen dates are indeed not needed. AVClass does not require them to be there in LB files. In fact, the README does not mention first_seen. scan_date is something I would recommend having there, but since it is not needed by AVClass, I have also removed the mention in the README.
