### ISSUE TITLE
Keyword normalization error?

### ISSUE THREAD

**Issue by xia0pin9** [malicialab/avclass#4]
It looks like there are some errors during the keyword normalization process. For instance, for the following samples ([1](https://www.virustotal.com/en/file/a026f49785847fc156e52c244f02a92f060a16862e6769ae89e6eaec5a59a11d/analysis/), [2](https://www.virustotal.com/en/file/f8e41450197d5d415fe6c465db1c348228d0fecbe93bdf885878d3b4d89af19a/analysis/), [3](https://www.virustotal.com/en/file/fde313b0f6595dfac2f9a7ddf563babac6a3cbcff618ec08532a989f646b6b25/analysis/), [4](https://www.virustotal.com/en/file/b186bdb6912bf1ad780254c6fc77a95d7cebc74955de53728186b13b1fb41ebc/analysis/)), I am expecting 8, 8, 9, 8 of "Zusy" keywords for each of them, but AVClass (with default configuration) only identified 2, 2, 3, 2 for them, and the third one is labeled as "valcaryx".

**Comment by malicialab** [comment]
Hi Yuping,
There is no error here, but if you read the paper AVClass first removes the identical labels to account for AV vendors copying the label from another. In your example #1 Ad-Aware, ALYac, BitDefender, F-Secure, GData, eScan and Emsisoft are considered the same given the identical value (the suffix (B) is first removed) and count as one, the other count comes from Arcabit.  

That being said, I have heard this comment from other users as well, so we are considering changing the default behavior to count the duplicates so that it better matches what people expect. Then, we can add a special flag to remove duplicates for interested users. We’ll try to implement this in the next days

Thanks,
Juan
