### ISSUE TITLE
AVClass2 PUP detection underestimates?

### ISSUE THREAD

**Issue by yigitcankaya** [malicialab/avclass#40]
PUP detection routine (in avclass2_common.py line 473) looks at a single CLASS tag for grayware but there are often multiple grayware tags such as:

0160b834b0939dffeedf1018296dd10e077743014d9724fb5020a4658f7330d9	72 FILE:os:windows|10,CLASS:grayware:adware|10,FAM:softcnapp|9,CLASS:grayware|8,UNK:burden|5,CLASS:virus|2	1

There are CLASS:grayware:adware|10 and CLASS:grayware|8, so should the PUP detection routine sum them up, instead of only looking at them individually?

**Comment by malicialab** [comment]
The function is_pup checks only whether the highest ranked CLASS tag contains "grayware" in the path. Thus, it should flag the sample you mention as PUP since the highest ranked CLASS tag is "CLASS:grayware:adware" that contains "grayware". Since it looks at the highest-ranked CLASS tag only, it does not sum them.

It is true that if there was a case like this:
CLASS:virus|10,CLASS:grayware:adware|8,CLASS:grayware|3 it would return false, when perhaps the answer should be true. 

Is that what you mean? Are you seeing cases like that one? If so, please share them.
