### ISSUE TITLE
Why 'Confidence' becomes a family name

### ISSUE THREAD

**Issue by LosSherl** [malicialab/avclass#7]
Some AVLabels are like 'malicious confidence 100%',  and the output family name turns out to be 'confidence', could you solve this problem?

**Comment by malicialab** [comment]
Can you share some hashes that manifest this behavior?
It would help to replicate and fix the issue

Best,
Juan

**Comment by rich7mcs** [comment]
It usually happens with the antivirus eGambit:
Here is an example:

https://www.virustotal.com/en/file/5f78a354e43f8fde34b72beb0e99b92048a9212e5a3c217d3bfe87a9a13e703e/analysis/

**Comment by LosSherl** [comment]
One single label doesn't really effect the outputs, and not just eGambit.
Here is an example:

https://www.virustotal.com/#/file/d994d5916446fa1b1c7b4ef3a8521e01b4379e23e8f0f044765fd232a62ccc89/detection

**Comment by malicialab** [comment]
We have added “confidence” to the default list of generics words in the data directory. Hopefully that addresses the issue. 
Keep in mind that you can always do this locally to see if solves your issue, but we are happy to integrate new generics and aliases so that the rest of users benefits. 

Feel free to let us know if this solves your issue. If we do not hear back we’ll close this issue in a few days

Best,
Juan

**Comment by LosSherl** [comment]
Thank you, I thought about this solution, but it's better to let you know.
